### ISSUE TITLE
Add pathfinder ose install instructions [1d]

### ISSUE THREAD

**Issue by noelo** [redhat-cop/pathfinder#1]

**Comment by texasbrok** [comment]
As a (Red Hat, partner, or customer) developer, I want to install Pathfinder on a system under my control so that I can develop fixes or enhancements to it.

**Comment by texasbrok** [comment]
As a (Red Hat, partner, or customer) developer, I want to install Pathfinder on a system under my control so that I can develop fixes or enhancements to it.

**Comment by texasbrok** [comment]
@noelo was this intended to be instructions solely for the OpenShift online instance?  Secondarily, can the "insturctions" take the form of an Ansible playbook?

**Comment by noelo** [comment]
Sure ansible could be used,  alas I don't know ansible so it'd be up to
someone else to do it.
I'm currently working on getting it as simple as possible to install. The
template does 99% of the work but there are some other commands that need
to be run in order to install it. Having these in a single playbook would
be great.

**Comment by matallen** [comment]
Initially this will take the form of bash scripts using "oc" to provision a complete environment in openshift (server, UI & mongo db). Instructions on how to use the bash scripts will be located in the README.md file of this project.

note: At a later date a story can be raised to convert to ansible if necessary.
