### ISSUE TITLE
Incorporate feedback from BU

### ISSUE THREAD

**Issue by noelo** [redhat-cop/pathfinder#11]
Feedback from Scott McCarthy

1. I noticed that might be useful to add would be around "Isolation" - similar to slide 12 [2]. Does it need process, container, virtual machine, physical machine, rack level, or data center level isolation? This could be for the main application or for a disaster recovery copy of the application. The question would apply to both the isolation of the main application or the DR copy.

For example, often corporate IT will isolate web service (dns, httpd, etc) applications in a separate VMware cluster from internal services (Oracle DBs, SAP, etc). This means, they trust virtualization, but not as much as they think. Subconsciously, sadly, many customers have made a design decision to isolate at the rack level by separating these groups of applications in separate physical clusters. Then for the DR copies of each, they will typically have different VMware clusters at the DR location, or fail over to separate VPCs in AWS.

Happy to have a quick call to discuss, but really that's the only major thing I see possibly missing...

2. Application restarts - can the application be killed and restarted cleanly. Some applications will restart very easily, like Apache/Nginx. Others can get much more finicky and crash or corrupt data, like MySQL, or Oracle Databases.

3. per CONFIG, I think this could be made a bit more sophisticated to include a question around if config files are changed by the application itself. For example, there are admin interfaces on a lot of software and they assume that they can write data and change the config. These files can sometimes be located all over the filesystem which makes them difficult to containerize.

4. Installation - source code compile, packages (RPM), installer script which can be reverse engineered, installer script which cannot be reverse engineered

5. The COMMS question doesn't capture raw TCP/UDP as a potential protocol. It also doesn't capture point to point encryption between containers (real request from BofA a while back). These make it more challenging to containerize

6. I would capture something around code/configuration/data. For example, MySQL has /usr/bin/mysqld, /etc/my.cnf /var/lib/mysql so it is really easy to containerize. Satellite 6, on the other hand, has about 75 configuration files, 20 storage directories, and 10 binaries. It makes it VERY difficult to put in a read only container with good bind mounts. Some apps are even worse. Many proprietary apps write data into strange places like /etc.

**Comment by texasbrok** [comment]
Progress?  Difficulty?  Rough remaining LOE?

**Comment by noelo** [comment]
4 hours
