### ISSUE TITLE
As any user, when not logged in (or timed out) user should be redirected to login page

### ISSUE THREAD

**Issue by matallen** [redhat-cop/pathfinder#113]
.. or at the very least a handler for 403 responses in the http xhr calls with a timed notification informing the user.

Also, the login username box should have the cursor ready to enter (it should be focus on page ready/load).

Also, there should be only one login screen (we currently have index and login.jsp)

**Comment by boogiespook** [comment]
I'm not a Java person but have found some examples of how it can be done:
https://coderanch.com/t/611948/java/Auto-redirect-session-timeout-page
https://stackoverflow.com/questions/1026846/how-to-redirect-to-login-page-when-session-is-expired-in-java-web-application
https://www.daniweb.com/programming/web-development/threads/282563/redirecting-to-login-page-after-session-timeout

**Comment by matallen** [comment]
Just spotted Chris' suggestions and will look into them before closing the ticket, however for the time being I've added an error handler on all datatables so when then get an error ajax response they redirect to login page.

Might be better if it could detect 403 errors though, will investigate further
