### ISSUE TITLE
login is not checking the password

### ISSUE THREAD

**Issue by matallen** [redhat-cop/pathfinder#123]
... you can use anything!

**Comment by matallen** [comment]
I remember not checking it on the token check/filter, but in order to get a token then the user & password needs to be checked. So the place to look into the code (assuming I dont grab this story) is the AuthenticationRestController.class /login method on the pathfinder-server & the authentication manager implementation

**Comment by matallen** [comment]
actually.... it's the CustomAuthenticationProvider.authenticate method.. That's the implementation but for some reason the password check isn't causing a failure. perhaps returning null on that method is not the correct approach...

**Comment by kelaird** [comment]
Now shows an error message if you put the wrong password in.
