### ISSUE TITLE
Unable to run under minishift out-of-the-box (fixes included)

### ISSUE THREAD

**Issue by ffirg** [redhat-cop/pathfinder#125]
minishift version
minishift v1.22.0+7163416

2 showstoppers. 

1) image streams are not available by default. Fixed with:
$ oc login -u system:admin
$ oc import-image redhat-openjdk-18/redhat-openjdk18-openshift:1.3 --from=registry.access.redhat.com/redhat-openjdk-18/openjdk18-openshift -n openshift --confirm
$ oc import-image jboss-webserver-31/jboss-webserver31-tomcat8-openshift:1.2 --from=registry.access.redhat.com/jboss-webserver-3/webserver31-tomcat8-openshift -n openshift --confirm

2) pathfinder-server needed more RAM. Had to set higher RAM limit, minishift delete and start
$ minishift config view
- cpus                               : 2
- memory                             : 8G
- vm-driver                          : virtualbox

**Comment by noelo** [comment]
Thanks @ffirg
