### ISSUE TITLE
Pathfinder Logo

### ISSUE THREAD

**Issue by kelaird** [redhat-cop/pathfinder#128]
We need marketing to create an official Pathfinder logo for the site and also so we can get some t-shirts ordered for RHTE.

**Comment by noelo** [comment]
@kelaird can this be close ?

**Comment by kelaird** [comment]
Yes

--------
*KERRIE LAIRD*

*SENIOR PRACTICE LEAD - CLOUD NATIVE DEV*

*EMEA SERVICES SOLUTIONS*

*https://www.redhat.com/* <https://www.redhat.com/>

*Red Hat UK Ltd, Peninsular House 30-36 Monument Street, 4th floorLondon
EC3R 8NB United Kingdom*

*klaird@redhat.com <klaird@redhat.com>    M: +44-7500-225222
<+44-7500-225222>    *
<https://red.ht/sig>

On 7 March 2019 at 11:35:02, noelo (notifications@github.com) wrote:

@kelaird <https://github.com/kelaird> can this be close ?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/redhat-cop/pathfinder/issues/128#issuecomment-470492625>,
or mute the thread
