### ISSUE TITLE
Ability to edit a Review

### ISSUE THREAD

**Issue by matallen** [redhat-cop/pathfinder#135]

**Comment by boogiespook** [comment]
If you edit an assessment (or review) and add some comments, they don't seem to appear on the viewAssessment page.  I've edited an assessment and added comments but they are not seen in: http://pathfinder-ui-pathfinder-dev.int.open.paas.redhat.com/pathfinder-ui/viewAssessment.jsp?app=ea7b3f28-3813-4550-b582-68a911150284&assessment=d82575c0-fa8c-4cda-b0f6-a765c1a9438f&customer=8bd7116d-c14c-44a6-b1db-5a38782246bc

**Comment by matallen** [comment]
fixed now - thanks for noticing that

**Comment by kelaird** [comment]
Working fine from both screens,
