### ISSUE TITLE
Move UI components to pathfinder-ui project

### ISSUE THREAD

**Issue by noelo** [redhat-cop/pathfinder#14]
Move the index.html and survey.js files. Pathfinder should not serve any ui artifacts

**Comment by texasbrok** [comment]
What does this buy us?  And what are progress and remaining effort?

**Comment by matallen** [comment]
components moved where possible. Survey moved back to the pathfinder project due to parsing of question ratings to provide json payloads for the UI, and the fact that at some point the questions may become spreadsheet driven.
