### ISSUE TITLE
Dependency Graph Colours Changing

### ISSUE THREAD

**Issue by kelaird** [redhat-cop/pathfinder#145]
When you select and de-select applications to appear in the Adoption Graph, their colours change.
Example can be seen here - if you select and de-select 'Legacy App1' you'll see the colours change:
http://pathfinder-ui-pathfinder-dev.int.open.paas.redhat.com/pathfinder-ui/report-quadrant.jsp?customerId=b354c697-5505-4193-bbcb-c23764200723

**Comment by matallen** [comment]
fixed in commit https://github.com/redhat-cop/pathfinder/commit/ff07f4d9768be4d4c0d7efaf73a24b816e5f0907

colors now stay the same whether its visible or not
