### ISSUE TITLE
Clearly define business vs work priority & add columns to the assessments screen

### ISSUE THREAD

**Issue by lpsantil** [redhat-cop/pathfinder#16]
Please add `Business Criticality` value in Question 1 in the Results screen.

**Comment by texasbrok** [comment]
@noelo I understand from @matallen that this may be complete.  Please close if you concur.

**Comment by matallen** [comment]
@noelo @kelaird 
We appear to be mixing our terms and creating confusion here I think.

In the survey the text states "business criticality" but the field name is BUSPRIORITY.

Priority vs Criticality means different things to the customer, an app can be critical but not their priority to migrate early.

Please could you (@noelo) state what you originally meant to convey with the question?
And also how it differs from the "business priority" and "work priority" in the assessment review screen?

Then after that we can determine what actions need to be taken for this story, and then it can be sized & prioritised ;-)

**Comment by lpsantil** [comment]
If it helps, I'll make `[A]dd a tooltip as to how [Business Criticality] affects scoring.` a separate RFE.  In retrospect it is more important to be able pull out what you put in to Pathfinder.  I imagine `Business Criticality` will be subjective on a per customer basis.

**Comment by matallen** [comment]
This field was to be part of the algorithm of how Pathfinder makes its recommendations and the output report. However we haven't defined the report aspect of Pathfinder yet, so the "how it affects scoring" hasn't been decided, but I take your point that there is a need to understand how answering certain questions affects that.

Yes please, do create an "Add a tooltip as to how [Business Criticality] affects scoring". That will force us to consider how we communicate to the end user how those fields affect the recommendations, whatever output we decide upon.
