### ISSUE TITLE
Generate customer report document

### ISSUE THREAD

**Issue by noelo** [redhat-cop/pathfinder#17]

**Comment by dstockdreher** [comment]
Make sure to include %/#  "unknown" answers in final reports.

**Comment by pathfinder-waffle** [comment]
As a customer I would like answers to the following 3 things:
Q1. What do I do with my app e.g. retain, refactor, replatform etc?
Q2. How complex is the work?
Q3. What are the dependencies?

As part of an output report which can be edited, I would like to see:
1. Summary of the Engagement
2. Customer Summary
3. Ready To Innovate output
4. Pathfinder Outputs:
Top Level
3 speedometer style  charts which shows:
- Easy effort to Migrate
- Medium effort to Migrate 
- Difficult effort to Migrate
Second Level
- Bubbles chart information (driven by what you select in the assessment)
- Dependencies Chart
Third Level
- Recommended Plan & approach driven by dependencies
5. Concerns & Risks
6. Next Steps
