### ISSUE TITLE
chart failing to render

### ISSUE THREAD

**Issue by martincsumner** [redhat-cop/pathfinder#180]
marking an application as database rather than assessable. then calling that same application from another as a dependency causes the bubble chart to fail to render.

From the error it would appear to be a index out of bounds related issue.

**Comment by matallen** [comment]
fixed in this commit - https://github.com/redhat-cop/pathfinder/commit/d30a2d5807090476bffcfa8fc754f788042343d1

**Comment by matallen** [comment]
The issue was caused by dependencies that had not been assessed and therefore their outbound dependencies was a null rather than a list. This was just poor handling of perfectly valid data, so a correction has been made and committed.
