### ISSUE TITLE
Add instructions to get it running on OSE CDK [1d]

### ISSUE THREAD

**Issue by noelo** [redhat-cop/pathfinder#2]

**Comment by texasbrok** [comment]
As a (Red Hat, partner, or customer) developer, I want to install Pathfinder on the OpenShift Container Development Kit so that I can develop fixes or enhancements to it.

**Comment by matallen** [comment]
For developer purposes I've created a script to deploy to an OSE project (including minishift as long as you have the templates).

It's as simple as "oc new-project <name>" followed by "./deploy.sh"

**Comment by matallen** [comment]
I've assigned this 1d of effort, just to check the scripts and have them signed off. I currently believe this work to be complete aside from any issues that arise from initial usage.
