### ISSUE TITLE
Add administrator UI

### ISSUE THREAD

**Issue by noelo** [redhat-cop/pathfinder#21]
Ability to CRUD customers
Ability to view statistics on customers, associated applications and reviews

**Comment by texasbrok** [comment]
@noelo is this complete?

**Comment by noelo** [comment]
@boogiespook ?

**Comment by matallen** [comment]
I'm going to say this is complete. We can now CRUD customers and their associated applications. In terms of stats, we can see the percentage of assessments complete and review assessments.
If there are any other stats that are required, please open a specific issue to cover it.
