### ISSUE TITLE
Add recommended approach per app

### ISSUE THREAD

**Issue by texasbrok** [redhat-cop/pathfinder#29]
As an application assessor in conjunction with the application owner I want to be able to designate an application to be cloud native, suitable for migration (lift and shift), suitable for modernisation (some rewrite) or not-container suitable

https://trello.com/c/85tzFKHv/28-as-an-application-assessor-in-conjunction-with-the-application-owner-i-want-to-be-able-to-designate-an-application-to-be-cloud-n

**Comment by texasbrok** [comment]
@noelo Kerrie thinks this might be complete.  Please confirm and, if so, close.

**Comment by noelo** [comment]
Done
