### ISSUE TITLE
Integrate with AMM tooling

### ISSUE THREAD

**Issue by texasbrok** [redhat-cop/pathfinder#31]
As a consultant, I want the assessment tool to integrate with existing Red Hat Application Migration and Modernisation initiatives and solutions.

The scorecard will attempt to integrate with existing Red Hat Application Migration and Modernisation initiatives and solutions (identifying potential candidates based on scorecard criteria and output). 

https://docs.google.com/document/d/1psn4PtxuJBn_GT2lKyobtAxpC49OvdO63bRMVvJmL0g

https://trello.com/c/vM63ZVz2/10-as-a-consultant-i-want-the-assessment-tool-to-integrate-with-existing-red-hat-application-migration-and-modernisation-initiative

**Comment by noelo** [comment]
Not needed at this stage
