### ISSUE TITLE
Make deployable in customer DC

### ISSUE THREAD

**Issue by texasbrok** [redhat-cop/pathfinder#32]
As a customer/consultant, I want the assessment tool to be deployable in the customer's data center.

https://trello.com/c/g54kWlSl/8-as-a-customer-consultant-i-want-the-assessment-tool-to-be-deployable-in-the-customers-data-center

**Comment by pathfinder-waffle** [comment]
@matallen I think this is completed with the close of #1 and the ability to deploy atomically on OSE with a single script
