### ISSUE TITLE
Develop architect enablement materials

### ISSUE THREAD

**Issue by texasbrok** [redhat-cop/pathfinder#33]
As a consultant, I have guidance inside or outside the tool that tells me how to complete this assessment process.

The methodology is published in some form so consultants can learn and understand it outside the specific implementation in any tool (e.g. nomenclature and artefact explanations within the tooling).

A scorecard application guides a consultant or customer through the methodology to determine its outputs (including for example workload name, suitability, level of effort, and prioritization).

https://docs.google.com/document/d/1psn4PtxuJBn_GT2lKyobtAxpC49OvdO63bRMVvJmL0g

https://trello.com/c/glGwxV5H/7-as-a-consultant-i-have-guidance-inside-or-outside-the-tool-that-tells-me-how-to-complete-this-assessment-process

**Comment by noelo** [comment]
@texasbrok can this be closed

**Comment by texasbrok** [comment]
@noelo no

Work began at https://docs.google.com/presentation/d/1-u4MfSExzwfiZSO7RluCiGOafCrykWYaq7DdWRyw82U/ but was overcome by other priorities in the in the fall

**Comment by kelaird** [comment]
Actually it can be now we have the new enablement videos.....

KERRIE LAIRD
Senior Practice Lead - Cloud Native Dev
EMEA Services Solutions
Red Hat 

Red Hat UK Ltd, Peninsular House 30-36 Monument Street, 4th floor
London EC3R 8NB United Kingdom
klaird@redhat.com    M: +44-7500-225222
