### ISSUE TITLE
Provide report of incomplete assessments (with "unknown" answers)

### ISSUE THREAD

**Issue by texasbrok** [redhat-cop/pathfinder#34]
As a business or application owner I want to be able to view application assessments which have questions that have "unknown" answers

https://trello.com/c/hjqS2YQc/38-as-a-business-or-application-owner-i-want-to-be-able-to-view-application-assessments-which-have-questions-that-have-unknown-answ

**Comment by texasbrok** [comment]
@noelo Kerrie thinks this might be complete. Please confirm and, if so, close.

**Comment by noelo** [comment]
No this isn't done.

**Comment by pathfinder-waffle** [comment]
Will add a new ticket for saving as incomplete.  This ticket is purely for adding a new column so can filter on Unknown.

**Comment by matallen** [comment]
![Untitled.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5b5ee5bb54d2660011ddd65b/125516c66e82c728ace21e0d46dd9a8e2a968fac8babf301b44fff9e2c4533317346f6292483b579e6412c070a5d1dac41585e16fffb8b2ea7e32e6c981e5ab38532022d8c6853beb2901eb80bbb25884d8cb0b58948c2e83c2cf5c6.png)
