### ISSUE TITLE
Add reporting for recommendation by category

### ISSUE THREAD

**Issue by texasbrok** [redhat-cop/pathfinder#35]
As a business owner I want to be able to view the entire application landscape in categories of cloud native, modernisable and unsuitable for containers

https://trello.com/c/ZwqccGuZ/36-as-a-business-owner-i-want-to-be-able-to-view-the-entire-application-landscape-in-categories-of-cloud-native-modernisable-and-un

**Comment by texasbrok** [comment]
@noelo Kerrie thinks this might be complete. Please confirm and, if so, close.

**Comment by noelo** [comment]
No this is not complete

**Comment by matallen** [comment]
this is the "current landscape" gauges on the top of the report

**Comment by kelaird** [comment]
OK
