### ISSUE TITLE
Add reporting for dependencies

### ISSUE THREAD

**Issue by texasbrok** [redhat-cop/pathfinder#36]
As a business owner I want to be able to view the breakdown of applications by dependency order

https://trello.com/c/xzpthRgm/35-as-a-business-owner-i-want-to-be-able-to-view-the-breakdown-of-applications-by-dependency-order

**Comment by texasbrok** [comment]
@noelo Kerrie thinks this might be complete. Please confirm and, if so, close.

**Comment by noelo** [comment]
Nope there is still work to be done on this to make it more presentable

**Comment by matallen** [comment]
@kelaird is this story satisfied by the "adoption plan" report? or do we need to complete the dependency lines on the bubble chart before we can close this story?

**Comment by kelaird** [comment]
@matallen yes this is fine, we can add the dependency lines on the bubble chart in a separate sprint.  Do we think the chart is enough to show the dependencies or should we put back the one Chris did?

**Comment by matallen** [comment]
dependency lines are complete on the bubble chart. 

To answer your question, I can only answer it with another im afraid. If the purpose of the dependency chart is to show the enormity and complexity of the current state, then we need a new chart.
If the purpose of the dependency chart is to show the dependencies of the "likely migration candidate apps" then the bubble chart is enough.

So are you trying to scare the customer or inform them?

If the latter, then we can close this, if the former then we need to keep it open.

**Comment by matallen** [comment]
story #8 is related to this one - if the answer is to inform the customer of dependencies as part the choosing the apps to migrate, then this story #36 can be closed, and also I think #8 can be too.

**Comment by kelaird** [comment]
@matallen lines on the bubbles are fine.  I was just suggesting adding another chart if it wasn't possible to put the lines on the bubbles.  This can be closed.
