### ISSUE TITLE
Add reporting for priority

### ISSUE THREAD

**Issue by texasbrok** [redhat-cop/pathfinder#37]
As a business owner I want to be able to view the breakdown of applications by business priority

https://trello.com/c/sQoZXiu0/34-as-a-business-owner-i-want-to-be-able-to-view-the-breakdown-of-applications-by-business-priority

**Comment by texasbrok** [comment]
@noelo Kerrie thinks this might be complete. Please confirm and, if so, close.

**Comment by boogiespook** [comment]
Add to Applications table.

**Comment by matallen** [comment]
business criticality (as renamed from priority) has been added to the apps table in the report page.  (it's also on the assessments summary table too for completeness)

**Comment by kelaird** [comment]
complete
