### ISSUE TITLE
Add reporting for work effort

### ISSUE THREAD

**Issue by texasbrok** [redhat-cop/pathfinder#38]
As a business owner I want to be able to view the breakdown of applications by work effort

https://trello.com/c/iMOVq5jk/33-as-a-business-owner-i-want-to-be-able-to-view-the-breakdown-of-applications-by-work-effort

**Comment by texasbrok** [comment]
@noelo Kerrie thinks this might be complete. Please confirm and, if so, close.

**Comment by noelo** [comment]
No not complete

**Comment by kelaird** [comment]
@matallen I think what we have is now fine.  I'll move across
