### ISSUE TITLE
Add ability to capture text

### ISSUE THREAD

**Issue by texasbrok** [redhat-cop/pathfinder#39]
As an application assessor in conjunction with the application owner I want to be able to add assessment notes, decisions and recommendations to the application assessment

https://trello.com/c/zRTtaZA8/30-as-an-application-assessor-in-conjunction-with-the-application-owner-i-want-to-be-able-to-add-assessment-notes-decisions-and-rec

**Comment by texasbrok** [comment]
@noelo Kerrie thinks this might be complete. Please confirm and, if so, close.

**Comment by noelo** [comment]
Notes can be added but they're not output as yet in a report
