### ISSUE TITLE
Create Developer guide

### ISSUE THREAD

**Issue by texasbrok** [redhat-cop/pathfinder#46]
As a developer, I want to build, run, and test Pathfinder.

**Comment by texasbrok** [comment]
Related to:
https://github.com/redhat-cop/pathfinder/issues/2

**Comment by matallen** [comment]
@texasbrok please take a look at the #2 commit comments and let me know if that satisfied this issue? I'm not sure whether this issue needs a document or a script to resolve it

**Comment by dstockdreher** [comment]
made small updates to correct order of ops for running locally in standalone vs. on minishift completely.
