### ISSUE TITLE
invalid json for empty customer for applicationAssessmentSummary rest call

### ISSUE THREAD

**Issue by matallen** [redhat-cop/pathfinder#52]
Assessment summary with no assessments (and no applications possibly?) returns a completely empty response (which is not valid json for the datatables we're using)

example request is:
/api/pathfinder/customers/c7686c0d-0db9-4297-9f17-08a9cf3f9a6e/applicationAssessmentSummary

Which causes an error on this page in the UI:
http://<server>/pathfinder-ui/results.jsp?customerId=c7686c0d-0db9-4297-9f17-08a9cf3f9a6e

### Replication:
* In the UI, create new customer
* click on the "view assessments" link for the new customer
* page throws a popup error because the datatable listing the app assessments fails to render due to the rest response

**Comment by noelo** [comment]
Fixed and verified
