### ISSUE TITLE
Quay in minishift standalone deployment process

### ISSUE THREAD

**Issue by matallen** [redhat-cop/pathfinder#68]
1) Identify if Quay is required in the standalone deployment of pathfinder on minishift.
This can be done by testing locally against a local, clean minishift instance.

**If the build of the server and/or UI is longer than 10 mins, then, and ONLY THEN do we need to consider the use of Quay.** Because it will increase the number of scripts to maintain.

Quay would be used in the build pipeline to push versioned binary copies into the Quay repo and deployment scripts would need to be updated to pull from Quay, thus creating a separate set of scripts to run for minishift install from the regular install.

2) update build process to push images to Quay
3) build ose deployment scripts and new templates configured to pull the image from Quay.

**Comment by noelo** [comment]
Pathfinder Images are now pushed to 
https://quay.io/repository/pathfinder/pathfinder-ui
https://quay.io/repository/pathfinder/pathfinder-server
