### ISSUE TITLE
Change "Review Date" from Epoch

### ISSUE THREAD

**Issue by boogiespook** [redhat-cop/pathfinder#71]
On the Assessment Summary page, the Review Date is showing at Epoch.  Need to change to a standard DTG.

**Comment by boogiespook** [comment]
For example: http://pathfinder-ui-vft-dashboard.int.open.paas.redhat.com/pathfinder-ui/assessments-v2.jsp?customerId=ba3e2f67-7f15-4c4f-ba29-e14fc8b71ff7

Shows Review Date as 1530332395536 which should be:  Saturday, 30 June 2018 04:19:55

**Comment by matallen** [comment]
fyi - date format config options are here: https://github.com/phstc/jquery-dateFormat
