### ISSUE TITLE
Provide a vision for Pathfinder's purpose and use

### ISSUE THREAD

**Issue by texasbrok** [redhat-cop/pathfinder#75]
As a Pathfinder developer, I want to understand what Pathfinder's purpose and field use are in order to make better decisions about Pathfinder architecture, design, and implementation.

**Comment by noelo** [comment]
@texasbrok can this be closed

**Comment by texasbrok** [comment]
@noelo yes.  see https://github.com/redhat-cop/pathfinder/blob/master/legacy/pathfinder-vision.rst
