### ISSUE TITLE
Bubble chart filtering

### ISSUE THREAD

**Issue by boogiespook** [redhat-cop/pathfinder#79]
Allow filtering within the Bubble chart

**Comment by matallen** [comment]
what kind of filtering do you want? we have filtering using the checkbox next to the app in the datatable list to the left of the bubble chart. that list is also orderable, so you can push the high business criticality apps to the top before checking the boxes, or any other field that the datatable shows.

**Comment by kelaird** [comment]
I think what we have is now OK as we have changed this since writing this requirement
