### ISSUE TITLE
Generate dependency tree

### ISSUE THREAD

**Issue by noelo** [redhat-cop/pathfinder#8]

**Comment by noelo** [comment]
Look at http://visjs.org/docs/network/#importing_data and using dot notation

**Comment by noelo** [comment]
Feedback from @boogiespook 

Node Array:
    nodes = new vis.DataSet([
        {id: 1, label: 'Big App', title: 'Application description and other stuff for the Big App', color: '#FF0000', effort: "High"},
        {id: 2, label: 'My Web App ', title: 'Web Application2 description and other stuff', color: "#7BE141", effort: "Low"},
        {id: 3, label: 'Backend Database', title: 'Application3 description and other stuff', color: '#FF0000', effort: "High"},
        {id: 4, label: 'Application 4', title: 'Application4 description and other stuff', color: '#7BE141', effort: "Low"},
        {id: 5, label: 'Application 5', title: 'Application5 description and other stuff', color: "#FCC200", effort: "Medium"},
        {id: 6, label: 'Application 6', title: 'Application6 description and other stuff!', color: "#FCC200", effort: "Medium"},
        {id: 7, label: 'Orphan Application', title: 'Orphan Application description and other stuff', color: '#7BE141', effort: "Low"},
        {id: 8, label: 'Application 8', title: 'Application8 description and other stuff', color: "#FCC200", effort: "Medium"},
        {id: 9, label: 'Application 9', title: 'Application9 description and other stuff', color: '#7BE141', effort: "Low"},
        {id: 10, label: 'Application 10', title: 'Application10 description and other stuff', color: '#7BE141', effort: "Low"}
    ]);

Edge Array:
   var edges = new vis.DataSet([
        {from: 1, to: 3},
        {from: 1, to: 2},
        {from: 2, to: 4, arrows: "from"},
        {from: 2, to: 5,arrows: "from", dashes:true},
        {from: 1, to: 5, arrows: "from"},
        {from: 1, to: 6, arrows: "to"},
        {from: 3, to: 6, arrows: "from"},
        {from: 4, to: 8, arrows: "from"},
        {from: 5, to: 8, arrows: "to", dashes:true},
        {from: 8, to: 10, arrows: "to"},
        {from: 9, to: 10},
        {from: 10, to: 3}
    ]);

**Comment by boogiespook** [comment]
If possible, also returning the business priority could be good:
{id: 10, label: 'Application 10', title: 'Application10 description and other stuff', color: '#7BE141', effort: "Low", businessPriority: "6"}

**Comment by texasbrok** [comment]
As an owner of many applications, I want to view a graph of the dependencies among them in order to inform the prioritization of any application updates.

Does that capture the spirit, @noelo?

And what are status and remaining effort, good sir?

**Comment by noelo** [comment]
This is already done in the backend and MVP in the UI. More tweaking is
required for the UI, say 3 days.
This really depends on what UI tweaking we're doing with the UI COP

**Comment by matallen** [comment]
I still think we need to brainstorm how this feature would be used and be most impactful.

1) which screen do we have it on?
  a) report is quite busy, and if the customer is looking for recommendations then it's superfluous to that
  b) should we have it on the assessment screen so it feeds into the assessment review decision?
  c) could it be printed as an appendix to the report (assuming it contains all apps)
2) how will it scale with thousands of apps?
  a) do we need to filter a small portion of apps to reduce the output? how to we decide which ones?

I have not size this due to the above outstanding considerations.
