### ISSUE TITLE
Complete MoJo page for Pathfinder

### ISSUE THREAD

**Issue by pathfinder-waffle** [redhat-cop/pathfinder#88]
Wireframe page is in place but needs to be updated:

https://mojo.redhat.com/docs/DOC-1173791

Needs to include internal and external collateral.

**Comment by kelaird** [comment]
Already created but needs to be added:
- Customer facing presentation
- Internal Proposition deck
- Financial Analysis (prob only for EMEA?)
- RTI Enablement

Needs creating:
- 'How to' guide for Architects
- Speaker notes for every question
- Reporting & Tracking

any others?

**Comment by texasbrok** [comment]
Added links for:
- Customer facing presentation
- Internal Proposition deck
- Financial Analysis
Added a bit of FEATURES/BENEFITS content.
Added link to draft vision document.

Shouldn't RTI enablement ultimately be on a separate Mojo page, @kelaird ?  I don't mind adding a link temporarily if you can send me one; all I found was a combined RTI/Navigate briefing deck.

Lastly, could you kindly clarify your intent for the "speaker notes" and the "reporting & tracking" content, please?

**Comment by kelaird** [comment]
Hi James,

Yes happy to link out to RTI - I need to check the right page but if we put a placeholder in just now it's cool.

The idea behind the speaker notes is to guide someone through doing the assessment with a customer, does that make sense?

The reporting and tracking - not sure how but would be good to show charts of how many assessments have been completed and even links to outputs.  I think this will need to be in another sprint though as the PaaS version needs to be in place for this and at the moment this version is running on laptops only.

I've put this card into In Progress too btw.

Kerrie

**Comment by texasbrok** [comment]
Thanks, Kerrie.

IIUC, then, we'd likely want to track the speaker notes under issue #41 

I'd also suggest we put the reporting and tracking under a new issue (assuming it isn't reflected somewhere already), since that feels like a distinct body of work.

Finally, I think the Architect How-To doc should be tracked under issue #33 

If we're in alignment on these points, all we need is the RTI info in order to close this issue out.  Please let me know your thoughts.

**Comment by noelo** [comment]
@texasbrok @kelaird can this be closed

**Comment by texasbrok** [comment]
@noelo yes, I consider it complete

**Comment by kelaird** [comment]
yes 

KERRIE LAIRD
Senior Practice Lead - Cloud Native Dev
EMEA Services Solutions
Red Hat 

Red Hat UK Ltd, Peninsular House 30-36 Monument Street, 4th floor
London EC3R 8NB United Kingdom
klaird@redhat.com    M: +44-7500-225222
